[package]
name = "client"
version = "0.1.0"
edition = "2021"

[features]
default = []
test_client = []

[dependencies]
common = { path = "../common" }

laminar = "0.5"
crossbeam-channel = "0.5"
log = "0.4"

[dev-dependencies]
client = { path = ".", features = ["test_client"] }
