[package]
name = "beetle"
description = "A Macroquad-Based Client for Shackle"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

macroquad = "0.3"
legion = "0.4"
crossbeam-channel = "0.5"
